name: hivetensor-backend
services:
- name: api
  git:
    repo_clone_url: https://github.com/HiveTensor/HivetensorWebsite.git
    branch: main
  source_dir: backend
  instance_count: 1
  instance_size_slug: basic-xxs
  dockerfile_path: backend/Dockerfile
  http_port: 8000
  health_check:
    http_path: /health
    period_seconds: 120
    timeout_seconds: 50
    initial_delay_seconds: 30
    success_threshold: 1
    failure_threshold: 2
    port: 8000

  envs:
  - key: DATABASE_URL
    scope: RUN_TIME
    type: SECRET
  - key: JWT_SECRET_KEY
    scope: RUN_TIME
    type: SECRET
  - key: CORS_ORIGINS
    scope: RUN_TIME
    value: "https://hivetensor.com,https://www.hivetensor.com"
  - key: ENVIRONMENT
    scope: RUN_TIME
    value: "production"

domains:
- domain: api.hivetensor.com
  type: PRIMARY 