name: hivetensor-backend
services:
- name: api
  git:
    repo_clone_url: https://github.com/HiveTensor/HivetensorWebsite.git
    branch: main
  source_dir: backend
  instance_count: 1
  instance_size_slug: basic-xxs
  dockerfile_path: backend/Dockerfile
  http_port: 8000
  envs:
  - key: DATABASE_URL
    scope: RUN_TIME
    type: SECRET
  - key: JWT_SECRET_KEY
    scope: RUN_TIME
    type: SECRET
  - key: CORS_ORIGINS
    scope: RUN_TIME
    value: "https://hivetensor.com,https://www.hivetensor.com"
  - key: ENVIRONMENT
    scope: RUN_TIME
    value: "production"

databases:
- engine: PG
  name: hivetensor-db
  num_nodes: 1
  size: basic-xs
  version: "14"

domains:
- domain: api.hivetensor.com
  type: PRIMARY 